### ISSUE TITLE
Bulleting doesn't auto-add new item on pressing enter

### ISSUE THREAD

**Issue by raveeshbhalla** [saket/press#25]
When I add a bullet, and press enter, I expect the next line to also be bulleted. It doesn't work, though at the moment.

**Comment by saket** [comment]
Agree. The editor is very dumb right now, but the main priority is to get cross-platform clients working. I want to see if I can somehow put rich formatting logic inside shared code. It's maths anyway.

**Comment by saket** [comment]
Turns out, the [maths](https://github.com/saket/press/blob/2f9f81fac8386aa8b8459a1d4b1aa919d851a32d/wysiwyg/src/commonTest/kotlin/me/saket/wysiwyg/formatting/AutoFormatOnEnterPressTest.kt#L126) isn't very hard. Here's a work-in-progress gif:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2387680/71347355-34a75800-2538-11ea-80cb-5bea15947172.gif)

**Comment by saket** [comment]
~~This is done. Will release a new update soon.~~ Released in [v1.3](https://github.com/saket/press/releases/tag/v1.3).
