### ISSUE TITLE
ADRs are more helpful when they are ADRs

### ISSUE THREAD

**Issue by deobald** [saket/press#49]
The standard directory structure of `/docs/arch/adr-001-xyz.md` isn't really necessary, but it's cleaner and the integer helps enforce their immutable intention.

I'd consider the standard `context` / `decision` / `status` / `consequences` structure to be non-optional if you want your ADRs to remain meaningful months or years from now.

**Comment by saket** [comment]
I initially wanted to structure them as ADRs but that felt like a lot of effort. I just wanted to offer a single document showing the _current_ state of doing things in the project. I don't really care much about documenting decisions that were made over time to reach the current state, especially because I have limited time to spend on this project and would prefer moving fast and breaking things 😄

**Comment by deobald** [comment]
Makes sense. I went back and looked at your docs and realized that the only mention of "Architecture Decision Records" was actually just the commit message. ;) Quick, close this issue before someone sees.

**Comment by saket** [comment]
![image](https://user-images.githubusercontent.com/2387680/83167968-ca927080-a0de-11ea-9397-4403c195b789.jpg)
